### ISSUE TITLE
Consider changing name from akka-safer-serializer to akka-serialization-helper

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/akka-safer-serializer#11]
The only problem I can see with this name is its acronym :trollface:

So probably `akka-borer-serializer` will be a better choice for PR/marketing reasons xD

_Originally posted by @PawelLipski in https://github.com/VirtusLab/akka-safer-serializer/pull/3#r619692378_

**Comment by PawelLipski** [comment]
Or `akka-better-`, `better-akka-`, `borer-akka-`, `safer-akka-`...

**Comment by PawelLipski** [comment]
Or `akka-serializability-helper` aka `ash` :pikachu:, esp. that most of the functionality is NOT going to be specific to Borer, and Borer-specific code should probably go directly into `sirthias/borer` repo instead

**Comment by MarconZet** [comment]
So what's the decision, are we doing it or not? `akka-serialization-helper` sounds nice to me. Do I have a green light to do it in #48?

**Comment by PawelLipski** [comment]
![image](https://user-images.githubusercontent.com/3383210/122407541-fef2fc00-cf81-11eb-8080-b962b3165082.png)
