### ISSUE TITLE
Provide a Borer codec for akka.stream.SourceRef

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/akka-safer-serializer#14]
[borer-compat-akka](https://sirthias.github.io/borer/borer-compat-akka.html) provides `io.bullet.borer.compat.akka#typedActorRefCodec` for `ActorRef`, but apparently nothing for `SourceRef` :/

**Comment by MarconZet** [comment]
The codec for `SourceRef` has been implemented. I've also created a codec for `SinkRef` for future use.
