### ISSUE TITLE
[Bug in Borer?] Field of a type that is an alias for a simple type crashes the derivation

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/akka-safer-serializer#16]
```
  type Foo = String
  case class Bar(bar: Foo)
  implicit val barCodec: Codec[Bar] = deriveCodec
```

crashes with:

```
[error] MyBorerAkkaSerializer.scala:54:39: value writeMyBorerAkkaSerializer.this.Foo is not a member of io.bullet.borer.Writer
[error]   implicit val barCodec: Codec[Bar] = deriveCodec
```

Apparently the derivation looks for `"write" + <typename>` method in Writer... which makes sense for `String`/`Double` etc. but not for type aliases. 

Pls check if that's still a problem in Borer 1.7.0; if so, pls open this issue in Borer + look for a workaround before it's fixed in Borer.

**Comment by MarconZet** [comment]
It seemes to be problem with `borer-derivation`, not `borer-core`.
The folowing code compiles:
```
type Foo = String
case class Bar(bar: Foo)
implicit val barCodec: Codec[Bar] = Codec(
  Encoder.from(Bar.unapply _),
  Decoder.from(Bar.apply _)
)
```

**Comment by MarconZet** [comment]
I've created an issue in the Borer repository: sirthias/borer#388

**Comment by sirthias** [comment]
This was indeed an issue in borer that is now fixed.
If you need a quick patch release I could publish one right away...

**Comment by PawelLipski** [comment]
Thanks for a quick response, yes if you could make a release we'd be grateful
