### ISSUE TITLE
Runtime safety - No checks whether message type extends custom trait associated with our serializer

### ISSUE THREAD

**Issue by MarconZet** [VirtusLab/akka-safer-serializer#8]
Akka determines what serialiser to use on what message based on the class of the message and its supertype. If a supertype is declared incorrectly, unexpected behaviour may occur.

**Comment by PawelLipski** [comment]
Hmmm could you provide a minimal repro? Esp. what you mean by _supertype is declared incorrectly_

**Comment by PawelLipski** [comment]
(@MarconZet bump)

**Comment by PawelLipski** [comment]
Duplicate of #5
